# Generated by Django 5.2.1 on 2025-05-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_aquisicao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('fornecedor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
